language: c
compiler:
- gcc
- clang
dist: trusty
sudo:
- required
before_install:
- git submodule update
- sudo apt-get -qq update
- uname -a
- sudo apt-get install -y build-essential libexpat-dev libgmp-dev libssl-dev libpcap-dev byacc flex git python-dev python-pastedeploy python-paste python-twisted
script:
- ./configure --disable-dpdk && make && make summary
