language: c
compiler:
- gcc
- clang
dist: trusty
sudo:
- required
before_install:
- git submodule update
- sudo apt-get -qq update
- uname -a
- sudo apt-get install -y unzip make coreutils gcc binutils build-essential libexpat1-dev libgmp-dev libncurses5-dev libssl-dev libpcap-dev byacc flex libreadline-dev python-dev python-pastedeploy python-paste python-twisted python-setuptools python-pip libxml2-dev libxslt-dev ethtool ruby jq gcovr
script:
- ./configure --disable-dpdk --enable-developer && make && make summary
